CREATE TABLE dummy (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(10) NULL,
                         status boolean NOT NULL DEFAULT true,
                         CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
                       id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       CONSTRAINT users_pkey PRIMARY KEY (id)
);