CREATE TABLE dummy (
                         id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(10) NULL,
                         status boolean NOT NULL DEFAULT true,
                         CONSTRAINT cliente_pkey PRIMARY KEY (id)
);